// MOCK — datos ficticios, no son datos reales de JaspeArt.
// Marcas, referencias, precios, stock y textos son inventados para validar la V1 visual.

import type { CatalogCategory, CatalogProduct } from "./types";

export const mockCategories: CatalogCategory[] = [
  {
    slug: "acuarela",
    name: "Acuarela",
    intro: "Color activado por agua.",
  },
];

export const mockProducts: CatalogProduct[] = [
  {
    slug: "ultramar-profundo-godet-entero",
    erpCode: "DEMO-AC-001",
    name: "Ultramar profundo",
    categorySlug: "acuarela",
    brand: "Atelier Demo",
    range: "Serie Pigmento",
    formatGroup: "atelier-ultramar-profundo",
    format: "Godet entero",
    colorName: "Azul ultramar",
    colorFamily: "Azules",
    swatch: "#1f2f9e",
    price: 9.4,
    stockQuantity: 7,
    specs: {
      pigment: "PB29",
      temperature: "Frío",
      transparency: "Transparente",
      granulation: "Alta",
      permanence: "I",
    },
    description:
      "Un azul de sedimento. Trabaja mejor cuando se le deja mover: en lavados amplios se separa del agua y se asienta en el grano del papel.",
    behavior:
      "Granula con claridad sobre papel de grano medio y grueso. En mezclas con tierras produce grises vivos que conservan la textura.",
    materialNote:
      "Al humedecerse, el pigmento se abre en una capa transparente y deja ver la granulación en las zonas de carga.",
    images: [],
  },
  {
    slug: "ultramar-profundo-medio-godet",
    erpCode: "DEMO-AC-002",
    name: "Ultramar profundo",
    categorySlug: "acuarela",
    brand: "Atelier Demo",
    range: "Serie Pigmento",
    formatGroup: "atelier-ultramar-profundo",
    format: "Medio godet",
    colorName: "Azul ultramar",
    colorFamily: "Azules",
    swatch: "#1f2f9e",
    price: 5.9,
    stockQuantity: 12,
    specs: {
      pigment: "PB29",
      temperature: "Frío",
      transparency: "Transparente",
      granulation: "Alta",
      permanence: "I",
    },
    description:
      "Un azul de sedimento en formato compacto para caja de campo. Mismo pigmento que el godet entero.",
    behavior:
      "Granula con claridad sobre papel de grano medio y grueso. Se reactiva con facilidad tras secar en la paleta.",
    images: [],
  },
  {
    slug: "ultramar-profundo-tubo-15-ml",
    erpCode: "DEMO-AC-003",
    name: "Ultramar profundo",
    categorySlug: "acuarela",
    brand: "Atelier Demo",
    range: "Serie Pigmento",
    formatGroup: "atelier-ultramar-profundo",
    format: "Tubo 15 ml",
    colorName: "Azul ultramar",
    colorFamily: "Azules",
    swatch: "#1f2f9e",
    price: 12.8,
    stockQuantity: 0,
    specs: {
      pigment: "PB29",
      temperature: "Frío",
      transparency: "Transparente",
      granulation: "Alta",
      permanence: "I",
    },
    description:
      "Un azul de sedimento en tubo, pensado para cargar mucho color en lavados grandes.",
    images: [],
  },
  {
    slug: "verde-oxido-de-cromo-tubo-5-ml",
    erpCode: "DEMO-AC-004",
    name: "Verde óxido de cromo",
    categorySlug: "acuarela",
    brand: "Taller Demo",
    range: "Serie Estudio",
    formatGroup: "taller-verde-oxido-cromo",
    format: "Tubo 5 ml",
    colorName: "Verde óxido de cromo",
    colorFamily: "Verdes",
    swatch: "#4f7a45",
    price: 11.9,
    stockQuantity: 7,
    specs: {
      pigment: "PG17",
      temperature: "Cálido",
      transparency: "Opaco",
      granulation: "Baja",
      permanence: "I",
    },
    description:
      "Un verde mineral opaco y sereno, formulado para mezclar con control sin perder presencia. Ofrece una masa de color limpia para paisajes, botánica y grises naturales.",
    behavior:
      "Cubre bien en una sola capa. Diluido, pierde intensidad antes que cuerpo; conviene trabajarlo en capas finas sobre fondos secos.",
    materialNote:
      "Sobre papel texturado, el mineral se posa en el grano con una variación tranquila y conserva los bordes.",
    images: [],
  },
  {
    slug: "verde-oxido-de-cromo-medio-godet",
    erpCode: "DEMO-AC-005",
    name: "Verde óxido de cromo",
    categorySlug: "acuarela",
    brand: "Taller Demo",
    range: "Serie Estudio",
    formatGroup: "taller-verde-oxido-cromo",
    format: "Medio godet",
    colorName: "Verde óxido de cromo",
    colorFamily: "Verdes",
    swatch: "#4f7a45",
    price: 6.5,
    stockQuantity: 0,
    specs: {
      pigment: "PG17",
      temperature: "Cálido",
      transparency: "Opaco",
      granulation: "Baja",
      permanence: "I",
    },
    description: "El mismo verde mineral en formato compacto.",
    images: [],
  },
  {
    slug: "azul-ftalo-tubo-5-ml",
    erpCode: "DEMO-AC-006",
    name: "Azul ftalo",
    categorySlug: "acuarela",
    brand: "Taller Demo",
    range: "Serie Estudio",
    format: "Tubo 5 ml",
    colorName: "Azul ftalocianina",
    colorFamily: "Azules",
    swatch: "#123f73",
    price: 9.8,
    stockQuantity: 20,
    specs: {
      pigment: "PB15:3",
      temperature: "Frío",
      transparency: "Transparente",
      granulation: "Nula",
      permanence: "I",
    },
    description:
      "Un azul intenso y limpio, de gran poder tintóreo. Una pequeña cantidad basta para teñir una mezcla.",
    behavior:
      "Tiñe el papel y no se levanta con facilidad. Ideal para veladuras transparentes y verdes de mezcla.",
    images: [],
  },
  {
    slug: "rojo-quinacridona-tubo-5-ml",
    erpCode: "DEMO-AC-007",
    name: "Rojo quinacridona",
    categorySlug: "acuarela",
    brand: "Estudio Demo",
    range: "Serie Color",
    format: "Tubo 5 ml",
    colorName: "Rojo quinacridona",
    colorFamily: "Rojos",
    swatch: "#a3203f",
    price: 10.4,
    stockQuantity: 3,
    specs: {
      pigment: "PV19",
      temperature: "Frío",
      transparency: "Transparente",
      granulation: "Nula",
      permanence: "II",
    },
    description:
      "Un rojo frío y luminoso que mantiene su limpieza en mezclas con azules y violetas.",
    images: [],
  },
  {
    slug: "amarillo-limon-medio-godet",
    erpCode: "DEMO-AC-008",
    name: "Amarillo limón",
    categorySlug: "acuarela",
    brand: "Estudio Demo",
    range: "Serie Color",
    format: "Medio godet",
    colorName: "Amarillo limón",
    colorFamily: "Amarillos",
    swatch: "#e7d23a",
    price: 5.6,
    stockQuantity: 11,
    specs: {
      pigment: "PY175",
      temperature: "Frío",
      transparency: "Semitransparente",
      granulation: "Nula",
    },
    description: "Un amarillo frío y ligero para verdes frescos y luces altas.",
    images: [],
  },
  {
    slug: "ocre-amarillo-godet-entero",
    erpCode: "DEMO-AC-009",
    name: "Ocre amarillo",
    categorySlug: "acuarela",
    brand: "Atelier Demo",
    range: "Serie Tierra",
    format: "Godet entero",
    colorName: "Ocre amarillo",
    colorFamily: "Tierras",
    swatch: "#b8773d",
    price: 7.9,
    stockQuantity: 9,
    specs: {
      pigment: "PY42",
      temperature: "Cálido",
      transparency: "Semiopaco",
      granulation: "Baja",
      permanence: "I",
    },
    description:
      "Color molido de origen mineral. Una tierra cálida y estable para bases, carnaciones y paisaje.",
    behavior:
      "Aporta cuerpo a las mezclas y suaviza los colores intensos sin ensuciarlos.",
    images: [],
  },
  {
    slug: "siena-tostada-godet-entero",
    erpCode: "DEMO-AC-010",
    name: "Siena tostada",
    categorySlug: "acuarela",
    brand: "Atelier Demo",
    range: "Serie Tierra",
    format: "Godet entero",
    colorName: "Siena tostada",
    colorFamily: "Tierras",
    swatch: "#8f4a2c",
    price: 8.2,
    stockQuantity: 15,
    specs: {
      pigment: "PBr7",
      temperature: "Cálido",
      transparency: "Semitransparente",
      granulation: "Media",
      permanence: "I",
    },
    description:
      "Una tierra rojiza y transparente que conserva el rastro de su procedencia en cada lavado.",
    images: [],
  },
  {
    slug: "sombra-tostada-tubo-15-ml",
    erpCode: "DEMO-AC-011",
    name: "Sombra tostada",
    categorySlug: "acuarela",
    brand: "Estudio Demo",
    range: "Serie Color",
    format: "Tubo 15 ml",
    colorName: "Sombra tostada",
    colorFamily: "Tierras",
    swatch: "#6a4a33",
    price: 10.7,
    stockQuantity: 4,
    specs: {
      pigment: "PBr7",
      temperature: "Cálido",
      transparency: "Semitransparente",
      granulation: "Media",
      permanence: "I",
    },
    description:
      "Un marrón profundo para oscurecer sin recurrir al negro. Mezclado con ultramar produce grises neutros.",
    images: [],
  },
];
